### ISSUE TITLE
[PS16] GML implementation

### ISSUE THREAD

**Issue by scmanjarrez** [IBM/libgroupsig#69]
Hi,
I have been testing the GML module, more specificly the export and import functions.

I'm having problems with the import of a GML with more than 1 member:

<details> 
<summary><b>debug code</b></summary>

```python
#!/usr/bin/env python3

from pygroupsig import constants
from pygroupsig import groupsig
from pygroupsig import gml
# import pdb
# pdb.set_trace()


group = groupsig.setup(constants.PS16_CODE)
print("No members: ", gml.gml_export(group['gml']))

step1_manager = groupsig.join_mgr(0,
                                  group['mgrkey'],
                                  group['grpkey'],
                                  gml=group['gml'])
step2_member = groupsig.join_mem(1,
                                 group['grpkey'],
                                 msgin=step1_manager)
user_memkey_empty = step2_member['memkey']
step3_manager = groupsig.join_mgr(2,
                                  group['mgrkey'],
                                  group['grpkey'],
                                  msgin=step2_member['msgout'],
                                  gml=group['gml'])
step4_member = groupsig.join_mem(3,
                                 group['grpkey'],
                                 msgin=step3_manager,
                                 memkey=user_memkey_empty)

gml_exp = gml.gml_export(group['gml'])
print("One member: ", gml_exp)

gml_imp = gml.gml_import(constants.PS16_CODE, gml_exp)
print("One member import: OK")

group['gml'] = gml_imp

step1_manager = groupsig.join_mgr(0,
                                  group['mgrkey'],
                                  group['grpkey'],
                                  gml=group['gml'])
step2_member = groupsig.join_mem(1,
                                 group['grpkey'],
                                 msgin=step1_manager)
user_memkey_empty = step2_member['memkey']
step3_manager = groupsig.join_mgr(2,
                                  group['mgrkey'],
                                  group['grpkey'],
                                  msgin=step2_member['msgout'],
                                  gml=group['gml'])
step4_member = groupsig.join_mem(3,
                                 group['grpkey'],
                                 msgin=step3_manager,
                                 memkey=user_memkey_empty)

gml_exp = gml.gml_export(group['gml'])
print("Two members: ", gml_exp)

gml_imp = gml.gml_import(constants.PS16_CODE, gml_exp)
print("Two members import: OK")

groupsig.clear(constants.GL19_CODE)
```
</details>

It fails importing the GML after inserting the second member.
```
No members:  b'AAAAAAAAAAA='
One member:  b'AQAAAAAAAAAAAAAAAAAAADAAAADPYkYi+UfapfCnQeeiN6+b2/eMNQmADJUzoWKKrv2aipyq/xVBguOsvN/JUpq2NJVgAAAAOTO8W7uxD4Co0u/IQQYk8U0G9Vxi5HOIbkdhTFT1+a6harAvxTbWFw7DNCrLGogSmRooEKLRv9HSxwXBFTm8ao2yCI/yska7ENq11xXufIkyw2TgnrcNcglxaYLPhdKUAAAAAA=='
One member import: OK
Two members:  b'AgAAAAAAAAAAAAAAAAAAADAAAADPYkYi+UfapfCnQeeiN6+b2/eMNQmADJUzoWKKrv2aipyq/xVBguOsvN/JUpq2NJVgAAAAOTO8W7uxD4Co0u/IQQYk8U0G9Vxi5HOIbkdhTFT1+a6harAvxTbWFw7DNCrLGogSmRooEKLRv9HSxwXBFTm8ao2yCI/yska7ENq11xXufIkyw2TgnrcNcglxaYLPhdKUAAAAAAEAAAAAAAAAMAAAAI3I0U85g89QBZKAAYGF21s2lE7R/h7bQ8VEeqWV2EyyXxwOB+zqn5LA/00XufIxB2AAAACL6a/OW9IZivBaEscSBPNzmsZPvI0Nd8fFfbaEcUCF6JRt3cb0UcT899o2OYtSNBeIqKxP6cDWEXtiX39zPFxz4/w3PeovUazDPSFB+X1aPDMHJzLTYL6x9BVemMU6RIQAAAAA'
Traceback (most recent call last):
  File "./test.py", line 60, in <module>
    gml_imp = gml.gml_import(constants.PS16_CODE, gml_exp)
  File "/home/schica/auditor/sergio/autoauditor/temp/test/lib/python3.6/site-packages/pygroupsig/gml.py", line 63, in gml_import
    raise Exception('Error importing GML.')
Exception: Error importing GML.
```

I have looked at the C implementation and got this information:
<details> 
<summary><b>debug output</b></summary> 

```
[P] No members:  b'AAAAAAAAAAA='
[P] One member:  b'AQAAAAAAAAAAAAAAAAAAADAAAADyv9qdF5CmAi+5pttNwEAd28Qrq7obmfPZ2FATDPUmvgn2H0m52LFWYg7/zi4LzBVgAAAA8osDsI9t+CdifFd128wTIFj82Xd1pfg1qW2ipxcx/CnegfRcugvxV2pCU1vR5CcMPEdJj2XqHfeL16lz0zICp+hcB5DLeQfdo67Step3H3h9zJnQFACizYAt5tZwNb8YAAAAAA=='

[C] gml_size: 172
[C] gml bytes: 0100000000000000000000000000000030000000F2BFDA9D1790A6022FB9A6DB4DC0401DDBC42BABBA1B99F3D9D850130CF526BE09F61F49B9D8B156620EFFCE2E0BCC1560000000F28B03B08F6DF827627C5775DBCC132058FCD97775A5F835A96DA2A71731FC29DE81F45CBA0BF1576A42535BD1E4270C3C47498F65EA1DF78BD7A973D33202A7E85C0790CB7907DDA3AED2B5EA771F787DCC99D01400A2CD802DE6D67035BF1800000000

[C] gml_entries: 1

[C] entry bytes
[C] entry id: 0000000000000000
[C] g1 data: 30000000F2BFDA9D1790A6022FB9A6DB4DC0401DDBC42BABBA1B99F3D9D850130CF526BE09F61F49B9D8B156620EFFCE2E0BCC15
[C] g2 data: 60000000F28B03B08F6DF827627C5775DBCC132058FCD97775A5F835A96DA2A71731FC29DE81F45CBA0BF1576A42535BD1E4270C3C47498F65EA1DF78BD7A973D33202A7E85C0790CB7907DDA3AED2B5EA771F787DCC99D01400A2CD802DE6D67035BF1800000000

[C] entry id: 0
[C] entry id (reserved size): 8
[C] len g1: 52
[C] len g2: 100
[C] entry id=0 size: 152 (160)

[P] One member import: OK

[P] Two members:  b'AgAAAAAAAAAAAAAAAAAAADAAAADyv9qdF5CmAi+5pttNwEAd28Qrq7obmfPZ2FATDPUmvgn2H0m52LFWYg7/zi4LzBVgAAAA8osDsI9t+CdifFd128wTIFj82Xd1pfg1qW2ipxcx/CnegfRcugvxV2pCU1vR5CcMPEdJj2XqHfeL16lz0zICp+hcB5DLeQfdo67Step3H3h9zJnQFACizYAt5tZwNb8YAAAAAAEAAAAAAAAAMAAAAE4QlImbGauEIGSKZeOoKgZarXTdEEbA9mrZvi0ePtO4tkQBiqfXm+oyzLAP2q91DmAAAAAxQaH0XjO9huL0irqwxrU261fIpqSQDmiEyNtGqp69F//2GE8AL6EN8uUKtWONehXpg/Vd4ejrV8yjb0eTCQnLMEg/b2OmS/Q+dZRHVCmAUo3Qmy2ZmtidMlD3S1jc7A4AAAAA'

[C] gml_size: 336
[C] gml_bytes: 0200000000000000000000000000000030000000F2BFDA9D1790A6022FB9A6DB4DC0401DDBC42BABBA1B99F3D9D850130CF526BE09F61F49B9D8B156620EFFCE2E0BCC1560000000F28B03B08F6DF827627C5775DBCC132058FCD97775A5F835A96DA2A71731FC29DE81F45CBA0BF1576A42535BD1E4270C3C47498F65EA1DF78BD7A973D33202A7E85C0790CB7907DDA3AED2B5EA771F787DCC99D01400A2CD802DE6D67035BF18000000000100000000000000300000004E1094899B19AB8420648A65E3A82A065AAD74DD1046C0F66AD9BE2D1E3ED3B8B644018AA7D79BEA32CCB00FDAAF750E600000003141A1F45E33BD86E2F48ABAB0C6B536EB57C8A6A4900E6884C8DB46AA9EBD17FFF6184F002FA10DF2E50AB5638D7A15E983F55DE1E8EB57CCA36F47930909CB30483F6F63A64BF43E759447542980528DD09B2D999AD89D3250F74B58DCEC0E00000000

[C] gml_entries: 2

[C] entry bytes
[C] entry id: 0000000000000000
[C] g1 data: 30000000F2BFDA9D1790A6022FB9A6DB4DC0401DDBC42BABBA1B99F3D9D850130CF526BE09F61F49B9D8B156620EFFCE2E0BCC15
[C] g2 data: 60000000F28B03B08F6DF827627C5775DBCC132058FCD97775A5F835A96DA2A71731FC29DE81F45CBA0BF1576A42535BD1E4270C3C47498F65EA1DF78BD7A973D33202A7E85C0790CB7907DDA3AED2B5EA771F787DCC99D01400A2CD802DE6D67035BF18000000000100000000000000300000004E1094899B19AB8420648A65E3A82A065AAD74DD1046C0F66AD9BE2D1E3ED3B8B644018AA7D79BEA32CCB00FDAAF750E600000003141A1F45E33BD86E2F48ABAB0C6B536EB57C8A6A4900E6884C8DB46AA9EBD17FFF6184F002FA10DF2E50AB5638D7A15E983F55DE1E8EB57CCA36F47930909CB30483F6F63A64BF43E759447542980528DD09B2D999AD89D3250F74B58DCEC0E00000000

[C] entry id: 0
[C] entry id (reserved size): 8
[C] len g1: 52
[C] len g2: 100
[C] entry id=0 size: 152 (160)

[C] entry bytes:
[C] entry id: 802DE6D67035BF18
[C] g1 data: 000000000100000000000000300000004E1094899B19AB8420648A65E3A82A065AAD74DD1046C0F66AD9BE2D1E3ED3B8B644018A
[C] g2 data: A7D79BEA32CCB00FDAAF750E600000003141A1F45E33BD86E2F48ABAB0C6B536EB57C8A6A4900E6884C8DB46AA9EBD17FFF6184F002FA10DF2E50AB5638D7A15E983F55DE1E8EB57CCA36F47930909CB30483F6F63A64BF43E759447542980528DD09B2D999AD89D3250F74B58DCEC0E00000000

[C] entry id: -689558144

Traceback (most recent call last):
  File "../../../../test.py", line 60, in <module>
    gml_imp = gml.gml_import(constants.PS16_CODE, gml_exp)
  File "/home/schica/auditor/sergio/autoauditor/libgroupsig/libgroupsig/pygroupsig/lib/python3.6/site-packages/pygroupsig/gml.py", line 63, in gml_import
    raise Exception('Error importing GML.')
Exception: Error importing GML.

```
</details>

I tried to understand how data is stored in the GML, but I couldn't find the remaining 4 bytes.
```
First GML: 
Total size: 172 bytes
Entries (n): 8 bytes
Entry (id): 8 bytes
Entry (0): 152 bytes
Missing (padding?): 4 bytes
```
```
Second GML:
Total size: 336 bytes
Entries (n): 8 bytes
Entry (id): 8 bytes
Entry (0): 152 bytes
Missing (padding?): 4 bytes
Entry (id): 8 bytes
Entry (1): 152 bytes
Missing (padding?): 4 bytes
```
I think the problem is caused by these missing bytes, that aren't taken into account when reading the entries from the imported GML, failing after the second entry.
E.g.
```
0200000000000000 -> 8 bytes (n entries)

0000000000000000 -> 8 bytes (entry id, 0)

30000000D5A8737EE57ACB9C220B6D2030C7CCB0B68DCAA4E7D980E981CD4704337BEE7C4692F711B409E7D270C37AA182231506 --> 52 bytes (G1, 0)

60000000A02C31D6AD87EE311704C6D27A04E05FFEF098010BC1DA86EDE50CDDDAD996B6D3A8EB3C1AF75FFD0645994B54DEE7010B10773435C49B14D1B7AB44C4903F5255DAE85DF2AA5A24C643EF104C9CA88807F7386EB35FAAFBF45C406E4B964411 --> 100 bytes (G2, 0)

00000000 --> 4 bytes (padding, 0)

0100000000000000 --> 8 bytes (entry id, 1)

30000000B1514455EF7ABFF55825EE0864013EB62EE6A8286F141034E5B45C36441BBB779BB7D0144DCF551943347B1953529803 --> 52 bytes (G1, 1)

60000000EB2ECDA1043F2AC07A75AEC7FFC91C10455535D8F930B6DF6A31BF607CC1B5307106B1613368CABB44A93FD4795E3111242218651DBBE20327A61085A11BBF68118AE0338CBB5701A296D9FEFCAF4996F4ED852742F29C44FB2660FEBABA011 --> 52 bytes (G2, 1)

000000000 --> 4 bytes (padding, 1)
```

**Comment by scmanjarrez** [comment]
I have added the padding and the entry-id size to the read size, and it seems to work:
 ```c
/* 4 is the padding I've seen, modifying ps16_gml_entry_get_size and the output varies the padding used */
read += entry_size + sizeof(gml->entries[i]->id) + 4;
```
```
One member:  b'AQAAAAAAAAAAAAAAAAAAADAAAADKW1PpSKDmwAlPxhQpc/31Zz04aCNs7X16WbpOaKYu6RFiPmPu6I7nIG7ZjHh/aQxgAAAAKAhAFHTcrdnSmFv1Oh58uCO0iW5tnQkPPNYwqjSrw9HMRqKK20lc8aDfYiQbyF
ILSDwkdeaqHxAZtf37/acfLNWoNhdIzV+tfoVLcgR2xQZapwrIKNmZkWoBk8aCcrqSAAAAAA=='
One member import: OK
Two members:  b'AgAAAAAAAAAAAAAAAAAAADAAAADKW1PpSKDmwAlPxhQpc/31Zz04aCNs7X16WbpOaKYu6RFiPmPu6I7nIG7ZjHh/aQxgAAAAKAhAFHTcrdnSmFv1Oh58uCO0iW5tnQkPPNYwqjSrw9HMRqKK20lc8aDfYiQby
FILSDwkdeaqHxAZtf37/acfLNWoNhdIzV+tfoVLcgR2xQZapwrIKNmZkWoBk8aCcrqSAAAAAAEAAAAAAAAAMAAAAAtheN2wRewbrHcy8g9jMsIwZ2w9IkZFNmo6rCKb6gKnIw6WakdOmL0qqyseLtCwEmAAAADk0XLatE14ty14RC
GFT6bKlvJpwfmYNtcFKriCD0mcH8tZvJ5RBpX5OcvjVXnmagwdXzVP5+1uND6wkYft20ILD8qlVfCLb69yAfmKgfk5D3uNtQSGMNq2LaN+PFhx8BIAAAAA'
Two members import: OK
...
Five members:  b'BQAAAAAAAAAAAAAAAAAAADAAAADKW1PpSKDmwAlPxhQpc/31Zz04aCNs7X16WbpOaKYu6RFiPmPu6I7nIG7ZjHh/aQxgAAAAKAhAFHTcrdnSmFv1Oh58uCO0iW5tnQkPPNYwqjSrw9HMRqKK20lc8aDfYiQb
yFILSDwkdeaqHxAZtf37/acfLNWoNhdIzV+tfoVLcgR2xQZapwrIKNmZkWoBk8aCcrqSAAAAAAEAAAAAAAAAMAAAAAtheN2wRewbrHcy8g9jMsIwZ2w9IkZFNmo6rCKb6gKnIw6WakdOmL0qqyseLtCwEmAAAADk0XLatE14ty14R
CGFT6bKlvJpwfmYNtcFKriCD0mcH8tZvJ5RBpX5OcvjVXnmagwdXzVP5+1uND6wkYft20ILD8qlVfCLb69yAfmKgfk5D3uNtQSGMNq2LaN+PFhx8BIAAAAAAgAAAAAAAAAwAAAA3cAWXpozmow8l0AUUflMnG7v9kL3ALhmHaxbtG
t+HkUB3ScfxdyNjK5nq4OEnw0EYAAAADxF94XSEF1UU3madl6nWmm3vebAAaS+cJnLCfKW/afEWEHIuMDXAUCXVHWgviIKC1fcaHcL9iOKRl8TRQGgfjwKT0X3TjXhj3pLjNuv2ykDD31YGgsn963eJPR/4H02BwAAAAADAAAAAAA
AADAAAADf8WcuFA4y1o6vJdsmLGIRXAseMZQ0fsHBc9Rl2UOpQfV/enNlXVe4XJuBwmfuiYZgAAAAfpganNgJR40ECpmD9pLLN+ndwVWGtpMca4S2AVjaHVKU0bfQ9J8KnGwfSwWdpv0WI9iWjmWEUh0p8NHzOrcULR8Zs6XPQ6ZF
ImUZP2i/dwJTdupa6+M/rpa55yurKJ2HAAAAAAQAAAAAAAAAMAAAAJOQkq6Rkc2SMAs9Yc80vWakh32DzsXh5DCG6zGuRc+kcXXKMKAUHccg3Snwss+lj2AAAADrocJbmhfJ4gvpGLY6gAggwUBVHrbjSzh56MGJ/WGG770jGO4h9
zNQa6/aUHEVmBmaUjkdWoINXXMD7joeTKJyOBMLaJQ4q/cTvBeAjciertEOw6RoZ4sE1Ik74xJvEI8AAAAA'
Five members import: OK
```

**Comment by scmanjarrez** [comment]
I have another doubt, if you export and import the GML without members, it fails, is that correct?
I have checked  `ps16_gml_export`, and it returns _something_ (AAAAAAAAAAA=) when the GML has no members, but it can't be imported, is that intented? If the b64 can't be imported, shouldn't it be forbidden in first place?

**Comment by jdv-ibm** [comment]
Hi, Sergio.

The export/import issue has been fixed in the new release. There was indeed a bug in the export/import functions of PS16 GMLs, which was causing a misalignment between the actual data, and what was being exported. This was in the core library, so it affected all wrappers.

I've pushed also a new version of the Python wrapper (version 1.1.0), which is already available via pip. 

Please, let me know if that works for you.

Thanks for your help! Your analysis and code was extremely helpful!
